name: CI/CD with GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: <tu-región>

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f path/to/your/kubernetes/manifests

      - name: Upload Python file to Kubernetes pod
        run: |
          kubectl cp path/to/your/python/file <pod-name>:/path/in/container

